'use client'

import { useState } from 'react'
import useSWR from 'swr'
import { Sparkles, RefreshCw } from 'lucide-react'
import type { AssetType } from '@/types'

const fetcher = (url: string) => fetch(url).then(r => r.json())

interface AICommentaryProps {
  symbol: string
  assetType: AssetType
}

export function AICommentary({ symbol, assetType }: AICommentaryProps) {
  const [refreshKey, setRefreshKey] = useState(0)

  const { data, isLoading, error } = useSWR<{ commentary: string; error?: string }>(
    `/api/market/commentary?symbol=${symbol}&assetType=${assetType}&v=${refreshKey}`,
    fetcher,
    { revalidateOnFocus: false }
  )

  const commentary = data?.commentary
  const isUnconfigured = data?.error === 'AI commentary not configured'

  if (isUnconfigured) return null

  return (
    <div className="card p-5 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-brand" />
          <h3 className="text-sm font-semibold text-text-primary">AI Commentary</h3>
        </div>
        <button
          onClick={() => setRefreshKey(k => k + 1)}
          disabled={isLoading}
          className="p-1.5 text-text-muted hover:text-text-primary hover:bg-surface-2 transition-colors disabled:opacity-40"
          title="Refresh"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {isLoading ? (
        <div className="space-y-2">
          <div className="h-3 bg-surface-2 animate-pulse w-full" />
          <div className="h-3 bg-surface-2 animate-pulse w-5/6" />
          <div className="h-3 bg-surface-2 animate-pulse w-4/6" />
        </div>
      ) : error || data?.error ? (
        <p className="text-xs text-text-muted">Error: {data?.error || 'Request failed'}</p>
      ) : commentary ? (
        <>
          <p className="text-sm text-text-secondary leading-relaxed">{commentary}</p>
          <p className="text-xs text-text-muted">
            Generated by Claude · Not financial advice
          </p>
        </>
      ) : null}
    </div>
  )
}
